In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/in_process/Games_coded.csv', index_col = 'game_id')

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [4]:
df.tail()

,min_players,max_players,avg_time,year,avg_rating,geek_rating,num_votes,age,owned,weight,...,Automatic Resource Growth,Prisoner's Dilemma,Narrative Choice / Paragraph,Contracts,Moving Multiple Units,King of the Hill,Force Commitment,Legacy Game,Bingo,Pattern Movement
game_id,,,,,,,,,,,,,,,,,,,,,
285265,2,4,60.0,2019,7.35792,6.02424,665.0,10,1171,2.3750,...,0,0,0,0,0,0,0,0,0,0
285774,1,4,90.0,2019,8.29442,7.52374,4935.0,14,9351,2.7381,...,0,0,0,0,0,0,0,0,0,0
285984,1,4,45.0,2019,7.77426,6.27306,794.0,14,1704,2.5217,...,0,0,0,0,0,0,0,0,0,0
286096,1,5,120.0,2019,7.49800,7.14207,7753.0,12,10970,2.8564,...,0,0,0,0,0,0,0,0,0,0
287954,2,4,45.0,2019,7.84646,7.01513,2731.0,8,5188,2.0132,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df.shape

(3836, 274)

In [6]:
df.iloc[:, :10].describe()

#Columns 11 through 273 are hot encoded categorical variables

,min_players,max_players,avg_time,year,avg_rating,geek_rating,num_votes,age,owned,weight
count,3836.000000,3836.000000,3836.000000,3836.000000,3836.000000,3836.000000,3836.000000,3836.000000,3836.000000,3836.000000
mean,2.010688,5.436131,82.510167,2007.887904,6.834371,6.222357,3387.934307,10.722888,5219.259124,2.217682
std,0.681773,7.278325,273.188526,10.636066,0.698512,0.539138,6615.109703,2.427055,9229.124746,0.782007
min,1.000000,1.000000,1.000000,1960.000000,3.331770,4.272580,500.000000,2.000000,263.000000,1.000000
25%,2.000000,4.000000,30.000000,2004.000000,6.421880,5.844862,770.000000,8.000000,1503.000000,1.590000
50%,2.000000,5.000000,60.000000,2011.000000,6.848635,6.109750,1345.500000,10.000000,2427.000000,2.150900
75%,2.000000,6.000000,90.000000,2015.000000,7.300432,6.523722,2936.250000,12.000000,4895.500000,2.730650
max,8.000000,100.000000,12000.000000,2020.000000,9.186900,8.576860,93524.000000,18.000000,139881.000000,4.723300

In [7]:
#Dependant variables are average rating and "geek rating"
#These are two different rating scales. They should be rather similar, so we'll use Average Rating for now
#The rest are possible inputs

X = df.drop(['avg_rating', 'geek_rating'], axis = 1)
y = df['avg_rating']
y2 = df['geek_rating']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .25, random_state = 42)

#Scale just the first 8 columns of training set. The rest are categorical
XScaled = X_train.iloc[:,:8]
col_names = XScaled.columns
XCats = X_train.iloc[:,8:] #columns with categorical variables
scaler = StandardScaler()
scaler.fit(XScaled)
XScaled = scaler.transform(XScaled)
X_train = pd.DataFrame(XScaled, columns = col_names, index = X_train.index)
X_train = X_train.join(XCats, how = 'left') #merge the scaled columns with the hot encoded columns
X_train.tail()

,min_players,max_players,avg_time,year,num_votes,age,owned,weight,Economic,Negotiation,...,Automatic Resource Growth,Prisoner's Dilemma,Narrative Choice / Paragraph,Contracts,Moving Multiple Units,King of the Hill,Force Commitment,Legacy Game,Bingo,Pattern Movement
game_id,,,,,,,,,,,,,,,,,,,,,
19995,0.002060,-0.058063,0.044059,-0.191676,-0.327848,0.530695,-0.428662,0.871417,0,0,...,0,0,0,0,0,0,0,0,0,0
27389,0.002060,0.365198,-0.237885,-0.191676,-0.347417,0.530695,-0.281476,-1.123985,0,0,...,0,0,0,0,0,0,0,0,0,0
8229,0.002060,-0.199150,-0.237885,-0.474665,-0.388147,-1.115016,-0.401695,-0.325080,0,0,...,0,0,0,0,0,0,0,0,0,0
232043,0.002060,-0.199150,-0.261380,0.845952,0.537188,-1.115016,0.978506,-0.149143,0,0,...,0,0,0,0,0,0,0,0,0,0
199383,1.484016,-0.058063,-0.026427,0.845952,-0.283140,-0.292161,-0.371782,0.828653,1,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
#Now we need to scale the Test Set using the same scaler we used on the training set
#Scale just the first 8 columns of test set. The rest are categorical
XScaled = X_test.iloc[:,:8]
col_names = XScaled.columns
XCats = X_test.iloc[:,8:] #columns with categorical variables
XScaled = scaler.transform(XScaled)
X_test = pd.DataFrame(XScaled, columns = col_names, index = X_test.index)
X_test = X_test.join(XCats, how = 'left') #merge the scaled columns with the hot encoded columns
X_test.tail()

,min_players,max_players,avg_time,year,num_votes,age,owned,weight,Economic,Negotiation,...,Automatic Resource Growth,Prisoner's Dilemma,Narrative Choice / Paragraph,Contracts,Moving Multiple Units,King of the Hill,Force Commitment,Legacy Game,Bingo,Pattern Movement
game_id,,,,,,,,,,,,,,,,,,,,,
21985,0.002060,-0.058063,-0.237885,-0.191676,-0.434287,-1.937872,-0.498120,-1.318928,0,0,...,0,0,0,0,0,0,0,0,0,0
1855,1.484016,0.647372,-0.096913,-1.606623,-0.391807,-1.115016,-0.349120,-1.446321,0,0,...,0,0,0,0,0,0,0,0,0,0
3655,0.002060,-0.199150,-0.096913,-0.568995,-0.318143,-1.526444,-0.288501,0.136465,0,0,...,0,0,0,0,0,0,0,0,0,0
126239,0.002060,0.083024,-0.143904,0.468633,-0.411535,-0.292161,-0.487696,0.242540,0,0,...,0,0,0,0,0,0,0,0,0,0
210232,-1.479895,-0.199150,1.312806,0.845952,-0.417899,-0.292161,-0.406114,1.682908,0,0,...,0,0,0,0,0,0,0,0,0,0